### ISSUE TITLE
Issue using seven talk

### ISSUE THREAD

**Issue by gaprat** [ddumont/seven#9] opened 2020-10-10 08:15 UTC
issue using seven talk where mules dont talk to npcs.

**Comment by gaprat** [comment] 2020-10-10 08:16
![image](https://user-images.githubusercontent.com/72647308/95650103-5239b400-0aaf-11eb-8570-99129ad8df2d.png)

**Comment by ddumont** [comment] 2020-10-10 13:45
Interesting...   Retail or private?

**Comment by gaprat** [comment] 2020-10-10 22:07
using it on retail

**Comment by ddumont** [comment] 2020-10-19 20:01
Interesting... well now that I'm not dealing with covid symptoms, I'll try to look into this.

**Comment by ddumont** [comment] 2020-10-19 20:07
Is this any npc?  Because I've used this on retail with some success...  never saw this error.
Do you have the npc targeted with the leader when you issue "/seven talk"?

Can you show me the ls chat logs for the leader and the mules?  maybe a bit more of the chat logs
Feel free to obfuscate the image to remove character names

**Comment by ddumont** [comment] 2020-10-19 20:08
also could you make sure that you're on the newest version?   Which version is it?

**Comment by gaprat** [comment] 2020-10-19 20:27
Should be the newest verion. It is any NPC. until recent update it worked flawlessly at the same NPCs

**Comment by gaprat** [comment] 2020-10-19 20:28
Im double checking verion but thats pretty much it for log it doesnt repeat mules like it used to when they would fail to find it just breaks. the command is sent from leader

**Comment by gaprat** [comment] 2020-10-19 20:35
![image](https://user-images.githubusercontent.com/72647308/96508716-0d3d1c80-1229-11eb-930d-2849197d4919.png)
![image](https://user-images.githubusercontent.com/72647308/96508785-1e862900-1229-11eb-823d-2ac34cbbc5a6.png)

**Comment by gaprat** [comment] 2020-10-19 20:36
the first try i did not have a proper target and it tried to find it but soon as i did it instantly broke. first pic is mule

**Comment by ddumont** [comment] 2020-10-19 20:44
I'll see if I can reproduce this with Shahayl

**Comment by ddumont** [comment] 2020-10-19 20:46
So it may have been that the first call put the addon into a bad state.
Can you try reloading the addon on all mules and the leader and try it again with a target selected?

**Comment by gaprat** [comment] 2020-10-19 20:58
seems to do the same thing

**Comment by ddumont** [comment] 2020-11-08 21:43
Haven't forgotten about you.   I got my retail sub and I'll go check it out soon.

My guess is that it's a special kind of talk packet that's different than most.
I haven't run into it often but I think there are some newer npcs where this happens

**Comment by gaprat** [comment] 2020-11-08 23:54
Awesome thank you so much.

**Comment by ddumont** [comment] 2020-12-02 02:02
@gaparat this should be fixed now!

**Closed as completed by ddumont** 2020-12-02 02:02 UTC

**Comment by gaprat** [comment] 2020-12-02 08:27
That's awesome thank you I'll try it when I get on tomorrow
